# Generated by Django 5.0.6 on 2026-06-30 10:06

import registration.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('passing_year', models.PositiveIntegerField(help_text='SSC / Passing Year')),
                ('department_class', models.CharField(help_text='e.g. Science / Commerce / Class 10-A', max_length=100)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('present_address', models.CharField(blank=True, max_length=255, null=True)),
                ('tshirt_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large'), ('XXL', 'XX-Large')], max_length=4)),
                ('registration_id', models.CharField(default=registration.models.generate_registration_id, editable=False, max_length=30, unique=True)),
                ('verify_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('transaction_id', models.CharField(max_length=64, unique=True)),
                ('sslcz_val_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sslcz_bank_tran_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sslcz_card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('ticket_pdf', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('ticket_emailed', models.BooleanField(default=False)),
                ('receipt_emailed', models.BooleanField(default=False)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
